import {
  BatchStatus,
  CourseStatus,
  UserRole,
  type ActivityLog,
  type Batch,
  type Course,
  type Inquiry,
  type Payment,
  type Settings,
  type Student,
  type Teacher,
  type User,
} from "./types";

export const INITIAL_DATABASE = {
  users: [
    { id: "U-1", name: "Admin User", email: "admin@dmrush.com", role: UserRole.Admin, isActive: true, password: "admin" },
    { id: "U-2", name: "Accountant User", email: "accountant@dmrush.com", role: UserRole.Accountant, isActive: true, password: "accountant" },
  ] as User[],
  courses: [
    { id: "C-101", name: "Global SEO Mastery", duration: "3 Months", totalFee: 30000, description: "Build compounding organic visibility with technical SEO, content systems, and authority.", status: CourseStatus.Active, portalCourseId: "course-global-seo", classesPerWeek: 3, days: "Mon/Wed/Sat", classTime: "12:00–1:30" },
    { id: "C-102", name: "Local SEO Mastery", duration: "3 Months", totalFee: 30000, description: "Win nearby demand with Maps, Google Business Profile, and location-focused pages.", status: CourseStatus.Active, portalCourseId: "course-local-seo", classesPerWeek: 3, days: "Mon/Wed/Sat", classTime: "1:30–3:00" },
    { id: "C-103", name: "Shopify & E-Commerce", duration: "2 Months", totalFee: 25000, description: "Build and optimize Shopify stores for product clarity, checkout flow, and growth.", status: CourseStatus.Active, portalCourseId: "course-shopify", classesPerWeek: 3, days: "Mon/Wed/Sat", classTime: "3:00–4:30" },
    { id: "C-104", name: "WordPress Website Development", duration: "3 Months", totalFee: 30000, description: "Build professional WordPress websites with clean structure, SEO foundations, and conversion focus.", status: CourseStatus.Active, portalCourseId: "course-wordpress", classesPerWeek: 3, days: "Mon/Wed/Sat", classTime: "4:30–6:00" },
    { id: "C-105", name: "AI Tools & Prompt Engineering", duration: "2 Months", totalFee: 20000, description: "Use modern AI tools with structured prompts for marketing and production work.", status: CourseStatus.Active, portalCourseId: "course-ai-tools", classesPerWeek: 3, days: "Tue/Thu/Sun", classTime: "12:00–1:30" },
    { id: "C-106", name: "SaaS-Based AI Tools", duration: "1 Month", totalFee: 15000, description: "Apply SaaS AI platforms for research, content, automation, and team workflows.", status: CourseStatus.Active, portalCourseId: "course-saas-ai", classesPerWeek: 3, days: "Tue/Thu/Sun", classTime: "1:30–3:00" },
    { id: "C-107", name: "Digital Marketing", duration: "2 Months", totalFee: 25000, description: "Plan and run digital marketing across search, social, content, and paid channels.", status: CourseStatus.Active, portalCourseId: "course-digital-marketing", classesPerWeek: 3, days: "Tue/Thu/Sun", classTime: "3:00–4:30" },
    { id: "C-108", name: "AI Website Building", duration: "1 Month", totalFee: 15000, description: "Design and ship modern websites faster with AI-assisted workflows.", status: CourseStatus.Active, portalCourseId: "course-ai-website", classesPerWeek: 2, days: "Tue/Thu", classTime: "4:30–6:00" },
  ] as Course[],
  batches: [
    { id: "B-101", courseId: "C-101", name: "GSEO-MWS-1200", startDate: "2026-08-01", endDate: "2026-11-01", capacity: 25, status: BatchStatus.Active },
    { id: "B-102", courseId: "C-102", name: "LSEO-MWS-1330", startDate: "2026-08-01", endDate: "2026-11-01", capacity: 25, status: BatchStatus.Active },
    { id: "B-103", courseId: "C-103", name: "SHOP-MWS-1500", startDate: "2026-08-01", endDate: "2026-10-01", capacity: 20, status: BatchStatus.Active },
    { id: "B-104", courseId: "C-104", name: "WP-MWS-1630", startDate: "2026-08-01", endDate: "2026-11-01", capacity: 20, status: BatchStatus.Active },
    { id: "B-105", courseId: "C-105", name: "AITOOLS-TTS-1200", startDate: "2026-08-01", endDate: "2026-10-01", capacity: 25, status: BatchStatus.Active },
    { id: "B-106", courseId: "C-106", name: "SAASAI-TTS-1330", startDate: "2026-08-01", endDate: "2026-09-01", capacity: 20, status: BatchStatus.Active },
    { id: "B-107", courseId: "C-107", name: "DMKT-TTS-1500", startDate: "2026-08-01", endDate: "2026-10-01", capacity: 25, status: BatchStatus.Active },
    { id: "B-108", courseId: "C-108", name: "AIWEB-TT-1630", startDate: "2026-08-01", endDate: "2026-09-01", capacity: 20, status: BatchStatus.Active },
  ] as Batch[],
  students: [] as Student[],
  inquiries: [] as Inquiry[],
  payments: [] as Payment[],
  logs: [] as ActivityLog[],
  settings: {
    instituteName: "DM Rush Institute",
    logoUrl: "",
    address: "Flat 101 Burj Al Ghauri Plaza, Faisal Colony Pattoki.",
    phone: "+92 301 7786667",
    email: "info@dmrush.edu.pk",
    currency: "PKR",
    timezone: "PKT (UTC+5)",
    receiptNote: "Thank you for choosing DM Rush. Please note that fees once paid are non-refundable and non-transferable.",
  } as Settings,
  teachers: [
    {
      id: "TCH-NAJAF",
      name: "Najaf Khan",
      email: "najaf.khan@dmrush.com",
      phone: "",
      roleTitle: "SEO, Marketing & Web Instructor",
      courseIds: ["C-101", "C-103", "C-104", "C-107"],
      isActive: true,
      createdAt: "2026-08-15T00:00:00.000Z",
      photoUrl: "/instructors/najaf-khan.png",
    },
    {
      id: "TCH-USMAN",
      name: "Usman Raza",
      email: "usman.raza@dmrush.com",
      phone: "",
      roleTitle: "AI & Local SEO Instructor",
      courseIds: ["C-102", "C-105", "C-106", "C-108"],
      isActive: true,
      createdAt: "2026-08-15T00:00:00.000Z",
      photoUrl: "/instructors/usman-raza.png",
    },
    {
      id: "TCH-TAYYAB",
      name: "Tayyab Hanif",
      email: "tayyab.hanif@dmrush.com",
      phone: "",
      roleTitle: "AI Tools Instructor",
      courseIds: [],
      isActive: true,
      createdAt: "2026-08-15T00:00:00.000Z",
      photoUrl: "/instructors/tayyab-hanif.png",
    },
  ] as Teacher[],
};
